-- 코드를 입력하세요
SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_INS A JOIN ANIMAL_OUTS B ON  A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY DATEDIFF(B.DATETIME, A.DATETIME) DESC
LIMIT 2

-- 보호기간 내림차순
# DATEDIFF(ANIMAL_OUTS.DATETIME, ANIMAL_INS.DATETIME)