# # -- 코드를 입력하세요
# SELECT HISTORY_ID, DAILY_FEE * (100 - DISCOUNT_RATE) * DATE_DIFF AS FEE
# FROM 
# ORDER BY FEE DESC, HISTORY_ID DESC





# # 자동차 대여일 계산
# DATEDIFF(B.END_DATE,B.START_DATE) + 1 AS DATE_DIFF

# # 얘를 활용해서
# # 할인까지 한 금액 FEE 계산
# # 일일 금액 * (100 - 할인율) * 대여 일수
# DAILY_FEE * (100 - DISCOUNT_RATE) * DATE_DIFF AS FEE # 테이블명 앞에 붙여야함

# 할인 적용.. 서브쿼리
SELECT HISTORY_ID, CASE 
WHEN DATEDIFF(B.END_DATE, B.START_DATE) +1 BETWEEN 7 AND 29 THEN ROUND(DAILY_FEE * 0.01 * (100 - (
SELECT DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE DURATION_TYPE = '7일 이상' AND CAR_TYPE = '트럭')) * (DATEDIFF(B.END_DATE,B.START_DATE) + 1),0)

WHEN DATEDIFF(B.END_DATE, B.START_DATE) +1 BETWEEN 30 AND 89 THEN ROUND(DAILY_FEE* 0.01 * (100 - (
SELECT DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE DURATION_TYPE = '30일 이상' AND CAR_TYPE = '트럭')) * (DATEDIFF(B.END_DATE,B.START_DATE) + 1),0)

WHEN DATEDIFF(B.END_DATE, B.START_DATE) +1 >= 90 THEN ROUND(DAILY_FEE * 0.01 * (100 - (
SELECT DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE DURATION_TYPE = '90일 이상' AND CAR_TYPE = '트럭')) * (DATEDIFF(B.END_DATE,B.START_DATE) + 1),0)

ELSE DAILY_FEE * (DATEDIFF(B.END_DATE,B.START_DATE) + 1)

END AS FEE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN C, CAR_RENTAL_COMPANY_CAR A  
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
WHERE A.CAR_TYPE = '트럭'
GROUP BY B.HISTORY_ID 
ORDER BY FEE DESC, HISTORY_ID DESC









# CASE WHEN DATEDIFF(B.END_DATE, B.START_DATE) +1 BETWEEN 7 AND 29 THEN DAILY_FEE * (100 - C.DISCOUNT_RATE) * DATE_DIFF
#     WHEN DATEDIFF(B.END_DATE, B.START_DATE) +1 BETWEEN 30 AND 89 THEN 
#     WHEN DATEDIFF(B.END_DATE, B.START_DATE) +1 >= 90 THEN >
#     WHEN DATEDIFF(B.END_DATE, B.START_DATE) +1 < 90 THEN  
#     END
    

