-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, count(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31' AND CAR_ID IN (
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31'
GROUP BY CAR_ID
HAVING count(HISTORY_ID) >= 5
)
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH(START_DATE), CAR_ID DESC


# -- 대여횟수 ..
# SELECT CAR_ID
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31'
# GROUP BY CAR_ID
# HAVING count(HISTORY_ID) >= 5
